<?php

namespace AppBundle\Repository\Reservation;

/**
 * TypeSalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeSalleRepository extends \Doctrine\ORM\EntityRepository
{
}
