AppBundle\Entity\Reservation\Salle:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\Reservation\SalleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        typeSalle:
            type: integer
        numeroSalle:
            type: string
            length: '1024'
        capaciteSalle:
            type: integer
    lifecycleCallbacks: {  }
