AppBundle\Entity\Reservation\Personne:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\Reservation\PersonneRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idNiveau:
            type: integer
        nom:
            type: string
            length: 255
        prenom:
            type: string
            length: 255
    lifecycleCallbacks: {  }
