AppBundle\Entity\Reservation\Niveau:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\Reservation\NiveauRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
            column: Nom
    lifecycleCallbacks: {  }
